spring.application.name=gateway
server.port=6000
jwt.secret=R4K1CLFUziVMsPkLiql8ciM7HTy1v6HN2ie2uzr1AcvPjFWk4J6BQqSydaUg1IAEW3FHUx44fLReKONZ9Lyj6w

coalas.users=4000
coalas.core=7000
coalas.loans=9000
server.address=localhost


