spring.application.name=gateway
server.port=6000
jwt.secret=R4K1CLFUziVMsPkLiql8ciM7HTy1v6HN2ie2uzr1AcvPjFWk4J6BQqSydaUg1IAEW3FHUx44fLReKONZ9Lyj6w
spring.main.web-application-type=reactive
coalas.users=users
coalas.core=core
coalas.loans=loans
server.address=tomcat.sonya.jij.li


